<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Models\Conversion;
use App\Models\PayoutRequest;
use App\Models\ReferralEarning;
use App\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Schema;

class ReferralController extends Controller
{
    public function dashboard(Request $request): JsonResponse
    {
        /** @var User $user */
        $user = $request->user();

        // Ensure user has referral_code
        if (empty($user->referral_code)) {
            $user->referral_code = 'REF' . strtoupper(\Illuminate\Support\Str::random(7));
            $user->save();
        }

        $referredUsersCount = User::where('referred_by', $user->id)->count();
        $activeReferredCount = User::where('referred_by', $user->id)->where('status', 'active')->count();

        $convertedReferredCount = 0;
        if (Schema::hasTable('conversions')) {
            $referredUserIds = User::where('referred_by', $user->id)->pluck('id');
            $convertedReferredCount = Conversion::whereIn('user_id', $referredUserIds)
                ->where('status', 'approved')
                ->distinct('user_id')
                ->count('user_id');
        }

        $totalReferralEarnings = 0.00;
        $pendingReferralEarnings = 0.00;

        if (Schema::hasTable('referral_earnings')) {
            $earnings = ReferralEarning::where('referrer_id', $user->id)->get();
            $totalReferralEarnings = (float) $earnings->where('status', 'approved')->sum('reward_amount');
            $pendingReferralEarnings = (float) $earnings->where('status', 'pending')->sum('reward_amount');
        }

        $referralUrl = config('app.url') . '/ref/' . $user->referral_code;

        return response()->json([
            'referral_code' => $user->referral_code,
            'referral_url' => $referralUrl,
            'stats' => [
                'total_referred' => $referredUsersCount,
                'active_referred' => $activeReferredCount,
                'converted_referred' => $convertedReferredCount,
                'total_referral_earnings' => $totalReferralEarnings,
                'pending_referral_earnings' => $pendingReferralEarnings,
            ],
            'current_rule' => [
                'type' => 'percentage',
                'value' => 10.00,
                'description' => 'Earn 10% commission on every conversion generated by your referred team members.',
            ]
        ]);
    }

    public function team(Request $request): JsonResponse
    {
        $user = $request->user();

        $members = User::where('referred_by', $user->id)
            ->select('id', 'public_id', 'name', 'email', 'mobile_number', 'status', 'created_at')
            ->latest()
            ->paginate(20);

        return response()->json($members);
    }

    public function earnings(Request $request): JsonResponse
    {
        $user = $request->user();

        if (!Schema::hasTable('referral_earnings')) {
            return response()->json(['data' => []]);
        }

        $earnings = ReferralEarning::with(['referredUser:id,name,email', 'conversion.campaign:id,name'])
            ->where('referrer_id', $user->id)
            ->latest()
            ->paginate(20);

        return response()->json($earnings);
    }
}
